//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributorMailSendler.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asp_Warehouses
    {
        public int Id { get; set; }
        public string KPP { get; set; }
        public string Name { get; set; }
        public long WarehouseCode { get; set; }
        public string Guid { get; set; }
        public Nullable<int> Distributor_Id { get; set; }
    
        public virtual Asp_SpravDistr Asp_SpravDistr { get; set; }
    }
}
