//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributorMailSendler.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistInvoices
    {
        public int Id { get; set; }
        public Nullable<double> AgentCode { get; set; }
        public string AgentCodeDistr { get; set; }
        public Nullable<int> DocNumber { get; set; }
        public string DocNumberDistr { get; set; }
        public string GUID { get; set; }
        public string Notes { get; set; }
        public System.DateTime OperDate { get; set; }
        public string OutletDistr { get; set; }
        public int OutletId { get; set; }
        public Nullable<double> PartnerFromCode { get; set; }
        public string PartnerFromCodeDistr { get; set; }
        public Nullable<double> PartnerToCode { get; set; }
        public string PartnerToCodeDistr { get; set; }
        public Nullable<int> RecId { get; set; }
        public bool Status { get; set; }
        public int TypeOper { get; set; }
    }
}
