//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributorMailSendler.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructionFiles
    {
        public int Id { get; set; }
        public int Sub_Id { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
        public string Name { get; set; }
        public string ContentType { get; set; }
    
        public virtual InstructionSubMenus InstructionSubMenus { get; set; }
    }
}
